config/routes.rb
Rails.application.routes.draw do

  resources :permissions
  resources :rols do
    member do
      post 'edit_status_permission'
    end
  end
  resources :populations
  resources :profiles do
    member do
      post 'edit_status_permission'
    end
  end
  resources :activities
  get 'home/index'

  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_status_permission]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @permissions = Permission.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /user/create
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to profiles_path(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

   # PATCH/PUT /users/1
   def update
    if @user.update(user_params)
      redirect_to profiles_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def edit_status_permission
    if params[:apply] && params[:apply] == "true"
      @user.permissions << Permission.find_by(:code => params[:code])
    else
      permission=@user.permissions.find_by(:code => params[:code])
      @user.permissions.delete(permission)
    end

    respond_to do | format |
      format.json {
        render json: {
          :message => 'ok'
        }
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :last_name, :date_birth, :rol_id, :email, :password, :password_confirmation)
    end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_form.html.erb
<% if @user.new_record?
path = profiles_path
else
  path = profile_path
end
%>
<%= form_for @user, :url => path do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
  </div>

  <div class="field">
    <%= form.label :date_birth %><br />
    <%= form.date_field :date_birth %>
  </div>

  <div class="form-group">
    <%= form.label :rol, class: 'contro-label' %>
    <div class="col-md-7">
      <div class="input-group">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-plane"></span>
        </span>
        <select name="user[rol_id]" id="user_rol"></select>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= form.submit "Sign up" %>
  </div>
<% end %>


<script type="text/javascript">
    $(document).ready(function(){
        $("#user_rol").select2({
            width: "330px",
            minimumInputlength: 1,
            debug: true,
            ajax: {
                url: "<%= rols_path(format: :json) %>",
                dataType: 'json',
                delay: 250,
                data: function (params){ 
                    return {
                        type: "select2",
                        q: params.term
                    };
                },
                processResults: function (data, page) {
                    return {
                        results: $.map(data, function (rol) {
                            return {
                                text:`${rol.name}`,
                                id: rol.id
                            }
                        })
                    }
                },
                cache:true
            },
            escapeMarkup: function (markup) { return markup; },
            theme: "bootstrap",
            placeholder: "Escriba un caracter"
        });
    });
    </script>

app/views/profiles/edit.html.erb
<h1>Profile#edit</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/profiles/index.html.erb
<h1>Profile#index</h1>
<p id="notice"><%= notice %></p>
<div class="row justify-content-center m-0 text-center">
  <div class="col-8 text-dark rounded p-4">
    <%= link_to 'Tabla de poblaciones', populations_path %>
    ||
    <%= link_to 'Tabla de actividades', activities_path %>
    ||
    <% if current_user.can?(TestTecnical::CREATE_USER) %>
      <%= link_to 'New User', new_profile_path %>
    <% end %>
    <h1>Users</h1>
      <br>
      <div class="row justify-content-center">
        <table class="table-border-less table-striped ">
        <thead class="bg-dark text-white rounded">
          </tr>
            <th class="p-3">Name</th>
            <th class="p-3">Last name</th>
            <th class="p-3">Rol</th>
            <th class="p-3">Email</th>
            <th class="p-3" colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="p-2" ><%= user.name %></td>
              <td class="p-2" ><%= user.last_name %></td>
              <td class="p-2" ><%= user.rol_id %></td>
              <td class="p-2" ><%= user.email %></td>
              <td class="p-2" ><%= link_to 'Show', profile_path(user) %></td>
              <td class="p-2" ><%= link_to 'Edit', edit_profile_path(user) %></td>
              <td class="p-2" ><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>Profile#new</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/profiles/show.html.erb
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
<div class="row justify-content-center m-0">
  <div class="col-4 bg-dark text-white rounded p-4">

  <%= hidden_field_tag 'user_id', @user.id %>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email :</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Rol:</strong>
      <%= @user.rol_id %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
    </div>
  </div>

    <table>
    <thead>
        <tr>
        <th>Name</th>
        <th> Apply</th>
        </tr>
    </thead>

    <tbody>
        <% @permissions.each do |permission| %>
        <tr>
          <td><%= permission.name %></td>
          <td><%= check_box_tag "permissions[apply][]", permission.code, @user.can?(permission.code), class: 'permissions_apply'%></td>
        </tr>
        <% end %>
    </tbody>
    </table>
    <script type="text/javascript">
    $(document).ready(function(){
      status_permission();
    });
    function status_permission(){
      $.each($(".permissions_apply"), function(index){
        $(this).click(function(){
          if($(this).is(":checked")){
              edit_status_permission({
                code: $(this).val(),
                apply: true,
                user_id: $("#user_id").val()
              })
          }
          else {
              edit_status_permission({
              code: $(this).val(),
              apply: false,
              user_id: $("#user_id").val()
              })
          }
      });
    });  
  }
  function edit_status_permission(oParams){
    $.ajax({
      url:"<%= edit_status_permission_profile_path(format: :json) %>",
      data: {
        id: oParams.user_id,
        code: oParams.code,
        apply: oParams.apply,
        authenticity_token: window._token
      },
      type: "POST",
      success: function(request){
        console.log(request);

        Swal.fire({
        position: 'center-center',
        icon: 'success',
        title: 'Your work has been saved',
        showConfirmButton: false,
        timer: 1500
        })

      },
      error: function(a, b, c){
        console.log(a);
        console.log(b);
        console.log(c);
        
        Swal.fire({
          position: 'top-end',
          icon: 'error',
          title: 'Your work not has been saved',
          showConfirmButton: false,
          timer: 1500
        })

      }
    })
  }
  
    </script>