config/routes.rb
Rails.application.routes.draw do

  resources :permissions
  resources :rols do
    member do
      post 'edit_status_permission'
    end
  end
  resources :populations
  resources :profiles do
    member do
      post 'edit_status_permission'
    end
  end
  resources :activities
  get 'home/index'

  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :permissions
  belongs_to :rol

  def can?(code)
    self.permissions.where(:code => code, :apply => true).exists? || self.rol.can?(code)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create

    build_resource(user_parems)

    if resource.save
      redirect_to root_path, notice: "usuario creado"
    else
      redirect_to root_path, notice: "usuario no creado"
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def user_parems
    params.require(:user).permit(:name, :last_name, :date_birth, :rol, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /user/create
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

   # PATCH/PUT /users/1
   def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
   def destroy
    @user.destroy
    redirect_to profiles_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_parems
      params.require(:user).permit(:name, :last_name, :date_birth, :rol, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.new_record?
path = profiles_path
else
  path = profile_path
end
%>
<%= form_for @user, :url => path do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
  </div>

  <div class="field">
    <%= form.label :date_birth %><br />
    <%= form.date_field :date_birth %>
  </div>

  <div class="form-group">
    <%= form.label :rol, class: 'contro-label' %>
    <div class="col-md-7">
      <div class="input-group">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-plane"></span>
        </span>
        <select name="user[rol_id]" id="user_rol"></select>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>


  <div class="actions">
    <%= form.submit "Sign up" %>
  </div>
<% end %>


<script type="text/javascript">
    $(document).ready(function(){
        $("#user_rol").select2({
            width: "330px",
            minimumInputlength: 1,
            debug: true,
            ajax: {
                url: "<%= rols_path(format: :json) %>",
                dataType: 'json',
                delay: 250,
                data: function (params){ 
                    return {
                        type: "select2",
                        q: params.term
                    };
                },
                processResults: function (data, page) {
                    return {
                        results: $.map(data, function (rol) {
                            return {
                                text:`${rol.name}`,
                                id: rol.id
                            }
                        })
                    }
                },
                cache:true
            },
            escapeMarkup: function (markup) { return markup; },
            theme: "bootstrap",
            placeholder: "Escriba un caracter"
        });
    });
    </script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center m-0 text-center">
  <div class="col-8 text-dark rounded p-4">
    <%= link_to 'Tabla de poblaciones', populations_path %>
    ||
    <%= link_to 'Tabla de actividades', activities_path %>
    ||
    <% if current_user.can?(TestTecnical::CREATE_USER) %>
      <%= link_to 'New User', new_user_path %>
    <% end %>
    <h1>Users</h1>
      <br>
      <div class="row justify-content-center">
        <table class="table-border-less table-striped ">
        <thead class="bg-dark text-white rounded">
          </tr>
            <th class="p-3">Name</th>
            <th class="p-3">Last name</th>
            <th class="p-3">Rol</th>
            <th class="p-3">Email</th>
            <th class="p-3" colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="p-2" ><%= user.name %></td>
              <td class="p-2" ><%= user.last_name %></td>
              <td class="p-2" ><%= user.rol_id %></td>
              <td class="p-2" ><%= user.email %></td>
              <td class="p-2" ><%= link_to 'Show', user %></td>
              <td class="p-2" ><%= link_to 'Edit', edit_user_path(user) %></td>
              <td class="p-2" ><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row justify-content-center m-0">
  <div class="col-4 bg-dark text-white rounded p-4">

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email :</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Rol:</strong>
      <%= @user.rol %>
    </p>


    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>