config/routes.rb
Rails.application.routes.draw do

  resources :permissions
  resources :rols do
    member do
      post 'edit_status_permission'
    end
  end
  resources :populations
  resources :profiles do
    member do
      post 'edit_status_permission'
    end
  end
  resources :activities
  get 'home/index'

  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activities
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:event_date, :name, :descrption, :place, :populations_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :activity_name %>
  </div>

  <div class="field">
    <%= form.label :descrption %>
    <%= form.text_field :descrption, id: :activity_descrption %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :activity_place %>
  </div>

  <div class="form-group">
    <%= form.label :populations_id, class: 'contro-label' %>
    <div class="col-md-7">
      <div class="input-group">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-plane"></span>
        </span>
        <select name="activity[populations_id]" id="activity_populations_id"></select>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){
        $("#activity_populations_id").select2({
            width: "330px",
            minimumInputlength: 1,
            debug: true,
            ajax: {
                url: "<%= populations_path(format: :json) %>",
                dataType: 'json',
                delay: 250,
                data: function (params){ 
                    return {
                        type: "select2",
                        q: params.term
                    };
                },
                processResults: function (data, page) {
                    return {
                        results: $.map(data, function (population) {
                            return {
                                text:`${population.type_population}`,
                                id: population.id
                            }
                        })
                    }
                },
                cache:true
            },
            escapeMarkup: function (markup) { return markup; },
            theme: "bootstrap",
            placeholder: "Escriba un caracter"
        });
    });
    </script>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row justify-content-center m-0 text-center">
  <div class="col-8 text-dark rounded p-4">
    <%= link_to 'Tabla de poblaciones', populations_path %>
    ||
    <%= link_to 'Tabla de usuarios', users_path %>
    ||
    <%= link_to 'New Activity', new_activity_path %>

    <h1>Activities</h1>

    <div class="row justify-content-center">
      <table class="table-border-less table-striped ">
        <thead class="bg-dark text-white rounded">
          </tr>
            <th class="p-3">Date</th>
            <th class="p-3">Name</th>
            <th class="p-3">Descrption</th>
            <th class="p-3">Place</th>
            <th class="p-3">Type population</th>
            <th class="p-3" colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @activities.each do |activity| %>
            <tr>
              <td class="p-2"><%= activity.event_date %></td>
              <td class="p-2"><%= activity.name %></td>
              <td class="p-2"><%= activity.descrption %></td>
              <td class="p-2"><%= activity.place %></td>
              <td class="p-2"><%= activity.populations_id %></td>
              <td class="p-2"><%= link_to 'Show', activity %></td>
              <td class="p-2"><%= link_to 'Edit', edit_activity_path(activity) %></td>
              <td class="p-2"><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @activity.event_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Descrption:</strong>
  <%= @activity.descrption %>
</p>

<p>
  <strong>Place:</strong>
  <%= @activity.place %>
</p>

<p>
  <strong>Type population:</strong>
  <%= @activity.populations_id %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>
<% else %>
    <p>No se ha iniciado session</p>
<% end %>