config/routes.rb
Rails.application.routes.draw do

  resources :permissions
  resources :rols do
    member do
      post 'edit_status_permission'
    end
  end
  resources :populations
  resources :profiles do
    member do
      post 'edit_status_permission'
    end
  end
  resources :activities
  get 'home/index'

  root to: "home#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/population.rb
class Population < ApplicationRecord

    # Methods
    def self.select2(q)
        select_scope = "id, type_population"
        where_scope = "LOWER(type_population) LIKE '%#{q.downcase}%'"
        select(select_scope).where(where_scope)
    end
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController
  before_action :set_population, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /populations
  def index
    @populations = Population.all
    respond_to do | format |
      format.html
      format.json {
        if params.has_key?(:type) && params[:type] == "select2"
          render json: Population.select2(params[:q])
        end
      }
    end
  end

  # GET /populations/1
  def show
  end

  # GET /populations/new
  def new
    @population = Population.new
  end

  # GET /populations/1/edit
  def edit
  end

  # POST /populations
  def create
    @population = Population.new(population_params)

    if @population.save
      redirect_to @population, notice: 'Population was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /populations/1
  def update
    if @population.update(population_params)
      redirect_to @population, notice: 'Population was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /populations/1
  def destroy
    @population.destroy
    redirect_to populations_url, notice: 'Population was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_population
      @population = Population.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def population_params
      params.require(:population).permit(:type_population, :age_init, :age_end)
    end
end

app/helpers/populations_helper.rb
module PopulationsHelper
end

app/views/populations/_form.html.erb
<%= form_with(model: population, local: true) do |form| %>
  <% if population.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(population.errors.count, "error") %> prohibited this population from being saved:</h2>

      <ul>
      <% population.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_population %>
    <%= form.text_field :type_population, id: :population_type_population %>
  </div>

  <div class="field">
    <%= form.label :age_init %>
    <%= form.number_field :age_init, id: :population_age_init %>
  </div>

  <div class="field">
    <%= form.label :age_end %>
    <%= form.number_field :age_end, id: :population_age_end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/populations/edit.html.erb
<h1>Editing Population</h1>

<%= render 'form', population: @population %>

<%= link_to 'Show', @population %> |
<%= link_to 'Back', populations_path %>

app/views/populations/index.html.erb
<div class="row justify-content-center m-0 text-center">
  <div class="col-8 text-dark rounded p-4">
    <%= link_to 'Tabla de actividades', activities_path %>
    ||
    <%= link_to 'Tabla de usuarios', users_path %>
    ||
    <%= link_to 'New Population', new_population_path %>
    <h1>Populations</h1>

    <div class="row justify-content-center">
      <table class="table-border-less table-striped ">
        <thead class="bg-dark text-white rounded">
          </tr>
            <th class="p-3">Type population</th>
            <th class="p-3">Age init</th>
            <th class="p-3">Age end</th>
            <th class="p-3" colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @populations.each do |population| %>
            <tr>
              <td class="p-2"><%= population.type_population %></td>
              <td class="p-2"><%= population.age_init %></td>
              <td class="p-2"><%= population.age_end %></td>
              <td class="p-2"><%= link_to 'Show', population %></td>
              <td class="p-2"><%= link_to 'Edit', edit_population_path(population) %></td>
              <td class="p-2"><%= link_to 'Destroy', population, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/populations/new.html.erb
<h1>New Population</h1>

<%= render 'form', population: @population %>

<%= link_to 'Back', populations_path %>

app/views/populations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type population:</strong>
  <%= @population.type_population %>
</p>

<p>
  <strong>Age init:</strong>
  <%= @population.age_init %>
</p>

<p>
  <strong>Age end:</strong>
  <%= @population.age_end %>
</p>

<%= link_to 'Edit', edit_population_path(@population) %> |
<%= link_to 'Back', populations_path %>